### ISSUE TITLE
Bug: User Cannot Input Enter Title Of Choice

### ISSUE THREAD

**Issue by kanz-creation** [arjitjohar/Group10Project#39]
Error Name: User Cannot Enter Title Of Choice

Version: Master – last commit id 733a623

Platform: Windows 10, x64

Description: Once the user selects the input file, and if they desire to choose a different title for their compostion, the converter does not pick up the changes. 

Steps to Reproduce:

1. Run The Application 
2. Select the tablature folder "Testing Inputs" 
3. Select any input file. 
4. Type a new title in the title box. 
5. Click convert. 

Expected: The musicXML file should have the title requested inside the musicXML file. 

Actual: The standard title named "Classical Guitar" shows. 

Priority: 5

Severity: Low

Screenshot: 

The window once the user has typed their personalized title: 
![image](https://user-images.githubusercontent.com/46408189/112537691-60da0600-8d85-11eb-93d1-c3ee17412b7d.png)

**Comment by arjitjohar** [comment]
Hey, kanz-creation, thank you for the bug report. This issue has now been fixed.
