### ISSUE TITLE
Bug: Text Files Outside Test Files Provided Do Not Work

### ISSUE THREAD

**Issue by kanz-creation** [arjitjohar/Group10Project#40]
Error Name: User Cannot Enter Choose Text File of Their Choice

Version: Master – last commit id 733a623

Platform: Windows 10, x64

Description: Once the user selects the input text file of their choice, the converter does not understand and detect the text file selected.  

Steps to Reproduce:

1. Open the Application. 
2. Select any tablature folder that is not "Testing Input" provided from the developer. 
3. Select any text input file for conversation. 
4. Click convert.

Expected: The musicXML file should have converted. 

Actual: The error window pops up indicating "please choose a file to convert" 

Priority: 1

Severity: High

Screenshot:

Selected input file before conversion: 
![image](https://user-images.githubusercontent.com/46408189/112538582-671cb200-8d86-11eb-9a64-0203eec12c86.png)

Selected input after clicking "convert": 
![image](https://user-images.githubusercontent.com/46408189/112538651-7ac81880-8d86-11eb-9581-b8967ec5728f.png)

**Comment by arjitjohar** [comment]
Hey, kanz-creation, thank you for the bug report. This issue has now been fixed.
